name: models
description: Data models with Freezed.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Các annotations để đánh dấu code
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Máy sinh code (Code Generator)
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
